name: Deploy Flutter Web

on:
  push:
    branches:
      - master  # or 'main' if your main branch is named 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ✅ Install Flutter from the master channel
      - uses: subosito/flutter-action@v2
        with:
          channel: master

      # ✅ Run Flutter commands
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release

      # ✅ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
